# =============================
#下载好文件名改为mpv.conf在导入！
#8.6日更新
#电视请勿使用此配置文件
#使用此配置文件必须确保自己设备支持Vulkan渲染！
#壳子中MPV播放性能-参数优先级-选择mpv.conf优先！
# 高画质 · 低延迟 · 低功耗
# ============================================================

    
# --- Vulkan 渲染架构（低延迟 & 高画质） ---
vulkan-swap-mode=mailbox
swapchain-depth=3
vulkan-queue-count=1
vulkan-async-compute=yes
vulkan-async-transfer=yes
video-latency-hacks=yes
gpu-dumb-mode=no
force-seekable=yes

# --- 核心画质设置（10bit / HDR / 抖动） ---
dither-depth=10
dither=fruit
temporal-dither=yes
fbo-format=rgba16f
video-output-levels=full
interpolation=no

#Spline16视频缩放放大算法，用于把低分辨率画面放大到高分辨率。特点是比默认的更清晰锐利
#总共有三档16 36 64，数值越大越清晰通透细腻，但功耗也会随着提升！
scale=spline16
cscale=spline16

#关闭AV1胶卷颗粒以提升清晰度，开启HDR10+元数据透传
vf=format:film-grain=no:hdr10plus=yes

#解码与渲染
hwdec=mediacodec
vo=gpu-next
gpu-api=vulkan
gpu-context=androidvk
video-sync=display-resample
hwdec-codecs=all


# --- 网盘网络优化（防限速/防断连） ---
network-timeout=60
stream-lavf-o=reconnect=1
stream-lavf-o=reconnect_at_eof=1
stream-lavf-o=reconnect_streamed=1
stream-lavf-o=reconnect_delay_max=4
stream-lavf-o=buffer_size=1310720
stream-lavf-o=rw_timeout=40000000
user-agent=Mozilla/5.0 (Android; Mobile) Chrome/120.0 Mobile Safari/537.36
demuxer-lavf-o=follow_redirects=1


#字幕音频相关
#让 MPV 播放视频时，优先加载中文音轨和中文字幕。
alang=zh,chi,chs,sc,zh-hans,en,eng
slang=zh,chi,chs,sc,zh-hans,en,eng
#字幕混合，字幕不会出现在黑边空白处！
blend-subtitles=yes
# 启动默认音量
volume=45
# 程序最大音量
volume-max=200

# 安卓低延迟高质量音频输出
ao=audiotrack
audio-channels=stereo
ad-lavc-downmix=yes
ad-lavc-ac3drc=0
audio-pitch-correction=yes
audio-format=float

#记性播放
save-position-on-quit
#关闭播放器时自动保存播放进度。
watch-later-options=start,vid,aid,sid
#进度文件保存内容：播放时间、视频轨道、音频轨道、字幕轨道。

#关闭日志输出，减少CPU读写，提升续航！
msg-level=all=no

#性能预设配置，稳定，流畅，省电。
profile=fast


#HDR直通 
target-colorspace-hint=yes
target-colorspace-hint-mode=source-dynamic
target-trc=pq
target-prim=bt.2020


[cache]
# 配置触发条件：仅网络流媒体启用该缓存配置
profile-cond=demuxer_via_network
# 开启缓存功能
cache=yes
# 播放器暂停时继续预加载缓存
cache-pause=yes
# 预缓存时长：300秒视频数据
cache-secs=300
# 最大向前缓存容量1024MB
demuxer-max-bytes=1024MiB
# 向后留存缓存上限1024MB
demuxer-max-back-bytes=1024MiB
# lavf底层参数：断网自动重连，已加载的流媒体也尝试重连，最长重连等待5秒
stream-lavf-o=reconnect=1,reconnect_streamed=1,reconnect_delay_max=5